config/routes.rb
Veggie::Application.routes.draw do
  
  
  resources :meals

  resources :common_allergens
  resources :dishes

  get "home/index"
  

  root :to => 'home#index'


end

app/models/common_allergen.rb
class CommonAllergen < ActiveRecord::Base
  has_and_belongs_to_many :dishes
  validates_presence_of :name
  attr_accessible :name, :dish_ids, :dishes
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  has_and_belongs_to_many :common_allergens
  has_and_belongs_to_many :meals
  validates_presence_of :name
  validates_presence_of :description
  attr_accessible :name, :description, :common_allergen_ids, :common_allergens
  
  def contains_allergen?(allergen)
    if self.common_allergens.include?(allergen)
      return true
    else
      return false
    end
  end
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  has_and_belongs_to_many :dishes
  validates_presence_of :name, :street_address, :city, :state, :zip_code
  validates_uniqueness_of :date, :message => "Only one meal is allowed on a given day. Please select a different date."
  attr_accessible :name, :description, :street_address, :city, :state, :pets, :notes, :date, :time, :zip_code
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/common_allergens_controller.rb
class CommonAllergensController < ApplicationController
  # GET /common_allergens
  # GET /common_allergens.json
  def index
    @common_allergens = CommonAllergen.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @common_allergens }
    end
  end

  # GET /common_allergens/1
  # GET /common_allergens/1.json
  def show
    @common_allergen = CommonAllergen.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @common_allergen }
    end
  end

  # GET /common_allergens/new
  # GET /common_allergens/new.json
  def new
    @common_allergen = CommonAllergen.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @common_allergen }
    end
  end

  # GET /common_allergens/1/edit
  def edit
    @common_allergen = CommonAllergen.find(params[:id])
  end

  # POST /common_allergens
  # POST /common_allergens.json
  def create
    @common_allergen = CommonAllergen.new(params[:common_allergen])

    respond_to do |format|
      if @common_allergen.save
        format.html { redirect_to @common_allergen, notice: 'Common allergen was successfully created.' }
        format.json { render json: @common_allergen, status: :created, location: @common_allergen }
      else
        format.html { render action: "new" }
        format.json { render json: @common_allergen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /common_allergens/1
  # PUT /common_allergens/1.json
  def update
    @common_allergen = CommonAllergen.find(params[:id])

    respond_to do |format|
      if @common_allergen.update_attributes(params[:common_allergen])
        format.html { redirect_to @common_allergen, notice: 'Common allergen was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @common_allergen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /common_allergens/1
  # DELETE /common_allergens/1.json
  def destroy
    @common_allergen = CommonAllergen.find(params[:id])
    @common_allergen.destroy

    respond_to do |format|
      format.html { redirect_to common_allergens_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dishes }
    end
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    @dish = Dish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.json
  def new
    @dish = Dish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
    @dish = Dish.find(params[:id])
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(params[:dish])

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render json: @dish, status: :created, location: @dish }
      else
        format.html { render action: "new" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.json
  def update
    @dish = Dish.find(params[:id])
    params[:dish][:common_allergen_ids] ||= []

    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meals }
    end
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    @meal = Meal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/new
  # GET /meals/new.json
  def new
    @meal = Meal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/1/edit
  def edit
    @meal = Meal.find(params[:id])
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(params[:meal])

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render json: @meal, status: :created, location: @meal }
      else
        format.html { render action: "new" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meals/1
  # PUT /meals/1.json
  def update
    
    @meal = Meal.find(params[:id])

    respond_to do |format|
      if @meal.update_attributes(params[:meal])
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/common_allergens_helper.rb
module CommonAllergensHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/common_allergens/_form.html.erb
<%= form_for(@common_allergen) do |f| %>
  <% if @common_allergen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@common_allergen.errors.count, "error") %> prohibited this common_allergen from being saved:</h2>

      <ul>
      <% @common_allergen.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/common_allergens/edit.html.erb
<h1>Editing common_allergen</h1>

<%= render 'form' %>

<%= link_to 'Show', @common_allergen %> |
<%= link_to 'Back', common_allergens_path %>

app/views/common_allergens/index.html.erb
<h1>Eating Restrictions and Common Allergens</h1>

<table>
  <tr>
    <th>Eating Restriction</th>
    <th>&nbsp;</th>
  </tr>

<% @common_allergens.each do |common_allergen| %>
  <tr>
    <td><%= link_to 'Show', common_allergen %>|<%= link_to 'Edit', edit_common_allergen_path(common_allergen) %>|<%= link_to 'Destroy', common_allergen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Common allergen', new_common_allergen_path %>

app/views/common_allergens/new.html.erb
<h1>New common_allergen</h1>

<%= render 'form' %>

<%= link_to 'Back', common_allergens_path %>

app/views/common_allergens/show.html.erb
<p id="notice"><%= notice %></p>
<%= @common_allergen.name %>

<%= link_to 'Edit', edit_common_allergen_path(@common_allergen) %> |
<%= link_to 'Back', common_allergens_path %>

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />
  <%= f.label :description %>:
  <%= f.text_field :description %><br />
  
  <% for common_allergen in CommonAllergen.find(:all) %>
  <div>
    <%= check_box_tag "dish[common_allergen_ids][]", common_allergen.id, @dish.common_allergens.include?(common_allergen) %>
    <%= common_allergen.name %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<h1>All Dishes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>&nbsp;</th>
  </tr>

<% @dishes.each do |dish| %>
  <tr>
    <td><%= dish.name %></td>
    <td><%= truncate(dish.description,:length => 50) %> </td>
    <td><%= link_to 'Show', dish %>|<%= link_to 'Edit', edit_dish_path(dish) %>|<%= link_to 'Delete', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>
<p> <%= @dish.name %> </p>
<p> <%= @dish.description %> </p>
<p> Eating restriction information: </p>
<% CommonAllergen.find(:all).each do |ca| %>
  <p> <%= ca.name %>: <%= @dish.contains_allergen?(ca) ? "Yes!" : "No" %> </p>
<% end %>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/home/index.html.erb
<h1>Veggie DC</h1>
<p>Website coming soon</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Veggie</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meals/_form.html.erb
<%= form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :name %>:
  <%= f.text_field :name %><br />
  A general description of the meal: <br />
  <%= f.text_field :description %><br />
  <%= f.label :street_address %>:
  <%= f.text_field :street_address %><br />
  <%= f.label :city %>:
  <%= f.text_field :city %><br />
  <%= f.label :state %>
  <%= f.select(:state, ["AL","AK","AS","AZ","AR","CA","CO","CT","DE","DC","FM","FL","GA","GU","HI","ID","IL","IN","IA","KS","KY","LA","ME","MH","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","MP","OH","OK","OR","PW","PA","PR","RI","SC","SD","TN","TX","UT","VT","VA","VI","WA","WV","WI","WY"])%><br />
  
  <%= f.label :zip_code %>:
  <%= f.text_field :zip_code %><br />
  
  Date: <%= date_select(:meal, :date, :default => 7.days.from_now) %> <br />
  
  Are there any animals living at the host's house? <br />
  <%= f.text_area :pets %><br />

  Any other notes? (for example, how to get in to the house)<br />
  <%= f.text_area :notes %><br />
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<h1>Listing meals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>&nbsp;</th>
  </tr>

<% @meals.each do |meal| %>
  <tr>
    <td><%= meal.name %></td>
    <td><%= "#{meal.date}, #{meal.time}"%></td>
    <td><%= link_to 'Show', meal %>|<%= link_to 'Edit', edit_meal_path(meal) %>|<%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>
<h1> <%= @meal.name %></h1> <br />
<%= @meal.description %> <br />
Date: <%="#{@meal.date}, #{@meal.time}"%> <br />
Location: <%= "#{@meal.street_address}, #{@meal.city}, #{@meal.state}" %><br />
Dishes: <%= @meal.dishes.map{|d| d.name}.join(",") %><br />
Does the host have pets? <%= @meal.pets.present? ? @meal.pets : "no pets" %><br />
Other notes: <%@meal.notes%><br />
<%= params %>
<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>